import turtle

turtle.shape('turtle')
turtle.speed(5)
# head
turtle.penup()
turtle.left(270)
turtle.forward(100)
turtle.right(270)
turtle.pendown()
turtle.color("black", "yellow")
turtle.begin_fill()
turtle.circle(120)
turtle.end_fill()
turtle.penup()
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(45)
# left eye
turtle.pendown()
turtle.color("black", "blue")
turtle.begin_fill()
turtle.circle(18)
turtle.end_fill()
turtle.penup()
turtle.left(180)
turtle.forward(90)
# right eye
turtle.left(180)
turtle.pendown()
turtle.begin_fill()
turtle.circle(18)
turtle.end_fill()
turtle.penup()
# nose
turtle.color('black')
turtle.forward(45)
turtle.left(90)
turtle.pensize(15)
turtle.pencolor("black")
turtle.forward(50)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
# mouth
turtle.color('red')
turtle.pencolor('red')
turtle.pendown()
turtle.circle(60, -180)
turtle.penup()

turtle.done()
